### ISSUE TITLE
Project Architecture

### ISSUE THREAD

**Issue by rashid-sial** [topcoderinc/TCO_Megahack_eRules_Search_Engine_Frontend#1]
Please complete the required updates to the project architecture today (11/11/16). Please see comments here: https://docs.google.com/document/d/1IcDnTY2Ly5AtzBJa5_iE1HVkBwYkam8o-7UQ5-wc8K4/edit

**Comment by coderReview** [comment]
Done.

**Comment by rashid-sial** [comment]
Thanks, I'm closing this ticket.
