### ISSUE TITLE
Addition to Rule Details Page Specification: Link to Regulations.gov

### ISSUE THREAD

**Issue by alamora** [topcoderinc/TCO_Megahack_eRules_Search_Engine_Frontend#15]
Add a box and a button to the screen in a prominent place:

_________________________________________
You can comment on this rule!  Click below to 
go to this rule on Regulations.gov and leave
your feedback.

[Comment on this Rule]   <---- this is a button
_________________________________________

To link the button, use the Docket ID.  Here's an example URL:
https://www.regulations.gov/document?D=EPA-HQ-OAR-2016-0598-0001

The docket ID is "EPA-HQ-OAR-2016-0598-0001"

**Comment by jarnanchen** [comment]
I added it to the top of details page, Is it OK?

![image](https://cloud.githubusercontent.com/assets/3425125/20253442/6897bd9e-aa66-11e6-8c2b-18be2fe56330.png)

**Comment by alamora** [comment]
Yup, that works - thank you!

**Comment by rashid-sial** [comment]
Fixed.
