### ISSUE TITLE
"Fills Automatically Based On State" - Needs correction

### ISSUE THREAD

**Issue by alamora** [topcoderinc/TCO_Megahack_eRules_Search_Engine_Frontend#17]
There are no attributes that fill automatically based on state.
See the [app sketch spreadsheet.](https://docs.google.com/spreadsheets/d/1O5MiuW6WbCa3IRSEwxen1pcqJbyM77tR62RW-hglIhk/edit#gid=0)

For convenience here's where the autocomplete fields need to come from.

**NAICS**: A pre-loaded list of all NAICS codes

**Substances**: A pre-loaded list of substances (can be pulled in realtime from the SRS API too, but, since we're focused on just the clean air act, we can also just preload the list from [Section 7412](https://www.law.cornell.edu/uscode/text/42/7412), as noted in the [overview doc](https://docs.google.com/document/d/1XGD4zrYNGV88pj07T6bB_k5v2l5PFxbMXhlEBMhcRTw/edit)

**Program Name**: A pre-loaded list of programs culled from the LRS xml.  Contestants will need to figure out how to do that.

**Comment by rashid-sial** [comment]
FYI @coderReview please note the above.

**Comment by alamora** [comment]
Did you intend to close this?
