### ISSUE TITLE
API Swagger Spec

### ISSUE THREAD

**Issue by rashid-sial** [topcoderinc/TCO_Megahack_eRules_Search_Engine_Frontend#2]
Please complete the swagger spec, it's due on 11//13/16.

**Comment by rashid-sial** [comment]
@coderReview what's the status of this?

**Comment by coderReview** [comment]
Fixed

**Comment by rashid-sial** [comment]
Completed and committed to https://github.com/topcoderinc/TCO_Megahack_API
