### ISSUE TITLE
Node.js Backend + API Integration Contest Spec 

### ISSUE THREAD

**Issue by rashid-sial** [topcoderinc/TCO_Megahack_eRules_Search_Engine_Frontend#3]
Complete the contest spec for the "Develop the backend & Node.js API (using Swagger) and integration with the regulations.gov API." contest. This is due on 11/14/16.

**Comment by coderReview** [comment]
Working on this

**Comment by coderReview** [comment]
Done. Please check https://docs.google.com/document/d/1JT5yofj4dnSr8a6XsbSEgsolzjzb5IpDzstOhnFzW5Q/edit#

**Comment by rashid-sial** [comment]
Approved. I've posted it to: https://www.topcoder.com/challenge-details/30055710/?type=develop&noncache=true
