### ISSUE TITLE
XML Parser Contest Spec

### ISSUE THREAD

**Issue by rashid-sial** [topcoderinc/TCO_Megahack_eRules_Search_Engine_Frontend#4]
Complete the contest spec for the "Develop the XML parser module (it'll use the Regulations.gov API response)" contest. This is due on 11/15/16.

**Comment by rashid-sial** [comment]
@coderReview will this be completed today?

**Comment by coderReview** [comment]
Yes

**Comment by rashid-sial** [comment]
Thanks, please keep me posted.

**Comment by coderReview** [comment]
Finished. Please check https://docs.google.com/document/d/14e1X_dWWpYE-M1ueJEeJtZLsoSEbHZ6fTSEJXBP4jVw/edit?usp=sharing

**Comment by rashid-sial** [comment]
Approved and posted to TC direct, also activated the challenge but it won't go live until the scheduled start time: http://www.topcoder.com/direct/contest/detail.action?projectId=30055711
