### ISSUE TITLE
Integration Contest Spec

### ISSUE THREAD

**Issue by rashid-sial** [topcoderinc/TCO_Megahack_eRules_Search_Engine_Frontend#5]
Complete the contest spec for the final integration contest. This is due on 11/16/17.

**Comment by rashid-sial** [comment]
@coderReview can you finish this tomorrow please?

**Comment by coderReview** [comment]
Fixed. See https://docs.google.com/document/d/1K6srqf9JCHZokAd_hGCNaawEyyIb9kNN8-og4A0s-kM/edit?usp=sharing

**Comment by rashid-sial** [comment]
Contest spec has been approved and posted to TC Direct: http://www.topcoder.com/direct/contest/detail.action?projectId=30055713. The contest has also been activated and is scheduled to launch on Sunday.
